# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
   schedule:
    - cron: '* * * * 5'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: test
      run: |
        python myPyTest.py
    - name: Send mail
      uses: dawidd6/action-send-mail@v2
      with:
       server_address: smtp.gmail.com
       server_port: 465
       username: meeting.user1poojitha@gmail.com
       password: P00jith@
       subject: Github Actions job result
       body: Build job of ${{github.repository}} completed successfully!
       to: poojitha.addanki@gmail.com
       from: Luke Skywalker # <user@example.com>
       # Optional content type (defaults to text/plain):
       content_type: text/html
       # Optional attachments:
       attachments: ./test.txt
